var dummyData=[
    {
    id:1,    
    name:"Lawn mower",
    category:"Garden",
    price:139,
    status:false,
    img:"https://thumbs.dreamstime.com/b/red-lawn-mower-isolated-white-background-d-render-red-lawn-mower-isolated-129799470.jpg",
    description:""
    },
    {
        id:2,
    name:"Rubber boots",
    category:"DIY",
    price:38,
    status:false,
    img:"https://www.westend61.de/images/0000110207pw/black-rubber-boots-on-white-background-MAEF003213.jpg",
    description:""
    },
    {
        id:3,
        name:"Rotary tool",
        category:"DIY",
    price:69,
    status:false,
    img:"https://image.shutterstock.com/image-photo/rotary-tools-accessory-focused-on-260nw-20413231.jpg",
description:""
    },
    {
        id:4,
    name:"Backpack",
    category:"Wear",
    price:73,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOnce_Both_Barrels_durable_backpack_1_720x.jpg?v=1599757290",
    description:""
    },
    {
        id:4,
    name:"Blue barrel",
    category:"DIY",
    price:12,
    status:false,
    img:"https://image.shutterstock.com/image-illustration/blue-plastic-storage-barrel-on-260nw-733438783.jpg",
    description:""
    },
    {
        id:5,
    name:"Heat gun",
    category:"DIY",
    price:27,
    status:false,
    img:"https://image.shutterstock.com/image-photo/new-heat-gun-on-white-260nw-324708014.jpg",
    description:""
    },
    {
        id:6,
    name:"Welder",
    category:"DIY",
    price:31,
    status:false,
    img:"https://www.pngfind.com/pngs/m/623-6237498_welder-png-stick-welder-transparent-png.png",
    description:""
    },
    {
        id:7,
    name:"Screwdriver set",
    category:"DIY",
    price:12,
    status:false,
    img:"https://live.staticflickr.com/65535/50396719177_867332f011_b.jpg",
    description:""
    },
    {
        id:8,
    name:"Sofa",
    category:"Home",
    price:163,
    status:false,
    img:"https://i.pinimg.com/originals/74/75/5a/74755a7835f0bcff26d39d6f09aee4c7.jpg",
    description:""
    },
    {
        id:9,
    name:"Desk",
    category:"Home",
    price:153,
    status:false,
    img:"https://www.pngkey.com/png/full/10-102719_corner-desk-minimalistic-ikea-corner-desk-2008.png",
    description:""
    },
    {
        id:10,
    name:"Lunch table",
    category:"Home",
    price:300,
    status:false,
    img:"https://www.ikea.com/es/en/images/products/danderyd-danderyd-table-and-6-chairs-pine-veneer-black-vissle-grey__1117977_pe872858_s5.jpg",
    description:""
    },
    {
        id:11,
    name:"Garden table",
    category:"Garden",
    price:600,
    status:false,
    img:"https://st4.depositphotos.com/3102107/22533/i/1600/depositphotos_225332358-stock-photo-wooden-table-chairs-isolated-white.jpg",
    description:""
    },
    {
        id:12,
    name:"lunch table",
    category:"Kitchen",
    price:200,
    status:false,
    img:"https://i.komnit.com/store/upload/images/production_900/9104-FYEAUC/1508386702-FYEAUC.jpg",
    description:""
    },
    {
        id:13,
    name:"Drill",
    category:"DIY",
    price:41,
    status:false,
    img:"https://img.freepik.com/premium-photo/drill-machine-isolated-white-background_44464-48.jpg?w=2000",
    description:""
    },
    {
        id:14,
    name:"Kitchen knives",
    category:"Kitchen",
    price:34,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/buymeonce_forest_forge_chefsbundle_ecomm_540x.jpg?v=1653498744",
    description:""
    },
    {
        id:15,
    name:"Socks",
    category:"Wear",
    price:12,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/12_540x.png?v=1653499924",
    description:""
    },
    {
        id:16,
    name:"Coffee machine",
    category:"Kitchen",
    price:22,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/horwood_ecomm-4_540x.jpg?v=1593301236",
    description:""
    },
    {
       id:17,
    name:"Raincoat",
    category:"Wear",
    price:34,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOnce_Graphene_ecomm5_540x.jpg?v=1633080561",
    description:""
    },
    {
       id:18,
    name:"Frying pan",
    category:"Kitchen",
    price:12,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOnce_SamuelGroves_castiron_ecomm2_540x.jpg?v=1630576345",
    description:""
    },
    {
       id:19,
    name:"Sunglasses",
    category:"Wear",
    price:52,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOne_Waterhaul_fitzroy_ecomm_540x.jpg?v=1617977961",
    description:""
    },
    {
        id:20,
    name:"Shaving razer",
    category:"Home",
    price:5,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOnce_Pincinox_ecomm2_540x.jpg?v=1665667474",
    description:""
    },
    {
        id:21,
    name:"Kitchen set",
    category:"Kitchen",
    price:43,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/TheSolidteknicsbestsellerPanSet3_540x.jpg?v=1657181000",
    description:""
    },
    {
       id:22,
    name:"Spatula",
    category:"Kitchen",
    price:7,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/SY04_540x.png?v=1586648285",
    description:""
    },
    {
        id:23,
    name:"Headphones",
    category:"Electronics",
    price:92,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOnce_Aiaiai_TMA-2MoveWireless_ecomm1_540x.jpg?v=1633971825",
    description:""
    },
    {
        id:24,
    name:"Toaster",
    category:"Electronics",
    price:134,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/Dualit_BuyMeOnce_repairable_toaster_4_slot_540x.jpg?v=1616599170",
    description:""
    },
    {
        id:25,
    name:"Power whisk",
    category:"Electronics",
    price:133,
    status:false,
    img:"https://cdn.shopify.com/s/files/1/2721/9324/products/BuyMeOnce_DualitHandMixer_ecomm_540x.jpg?v=1626691649",
    description:""
    },
    {
        id:26,
    name:"Wrench",
    category:"DIY",
    price:12,
    status:false,
    img:"https://freerangestock.com/sample/32750/an-adjustable-wrench-isolated-on-a-white-background.jpg",
    description:""
    }
    ]
    export default dummyData;